name: Pull request
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/install@v0.1
        with:
          crate: convco
          version: latest
      - name: Validate commit messages
        run: convco check ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}