name: convco

on:
  push:
    branches:

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: convco
    run: 'convco check "v4.0.0..HEAD"'
    secrets:
      private_key: ${{secrets.private_key}}
